[package]
name = "leptos-starter"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.8.15", features = ["csr"] }
leptos_router = "0.8.11"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt", "json"] }
